services:
  traefik:
    image: traefik:v3.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/config:/etc/traefik
    networks:
      - atoma-network

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - atoma-network

  atoma-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRACE_LEVEL: ${TRACE_LEVEL:-info}
    volumes:
      - ${CONFIG_PATH:-./config.toml}:/app/config.toml
      - ./logs:/app/logs
      - sui-config-volume:/root/.sui/sui_config
      - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/tmp/.sui/sui_config
    env_file:
      - .env
    ports:
      - "${ATOMA_PROXY_SERVICE_PORT:-8081}:8081"
    depends_on:
      - db
    networks:
      - atoma-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atoma-proxy.rule=Host(`${PROXY_DOMAIN:-api.atomacloud.com}`)"
      - "traefik.http.routers.atoma-proxy.entrypoints=websecure"
      - "traefik.http.routers.atoma-proxy.tls.certresolver=myresolver"
      - "traefik.http.routers.atoma-proxy.middlewares=secure-headers"
      - "traefik.http.services.atoma-proxy.loadbalancer.server.port=8080"

  atoma-dashboard:
    image: ${DASHBOARD_IMAGE:-atomacloud/dashboard:latest}
    networks:
      - atoma-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atoma-dashboard.rule=Host(`${DASHBOARD_DOMAIN:-atomacloud.com}`)"
      - "traefik.http.routers.atoma-dashboard.entrypoints=websecure"
      - "traefik.http.routers.atoma-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.atoma-dashboard.middlewares=secure-headers"
    restart: always

volumes:
  postgres-data:
  sui-config-volume:

networks:
  atoma-network:
    driver: bridge
