services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - atoma-network

  atoma-proxy:
    image: ghcr.io/atoma-network/atoma-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
       TRACE_LEVEL: ${TRACE_LEVEL:-info}
    volumes:
      - ${CONFIG_PATH:-./config.toml}:/app/config.toml
      - ./logs:/app/logs
      - sui-config-volume:/root/.sui/sui_config
      - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/tmp/.sui/sui_config
    env_file:
      - .env
    ports:
      - "${ATOMA_SERVICE_PORT:-8080}:8080"  # Expose Atoma service port
    depends_on:
      - db
    networks:
      - atoma-network

volumes:
  postgres-data:
  sui-config-volume:

networks:
  atoma-network:
    driver: bridge
