services:
  traefik:
    image: traefik:v3.3.0-rc2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - atoma-network

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - atoma-network

  atoma-proxy:
    image: ghcr.io/atoma-network/atoma-proxy:latest
    volumes:
      - ${CONFIG_PATH:-./config.toml}:/app/config.toml
      - ./logs:/app/logs
      - sui-config-volume:/root/.sui/sui_config
      - ${SUI_CONFIG_PATH:-~/.sui/sui_config}:/tmp/.sui/sui_config
    env_file:
      - .env
    ports:
      - "${ATOMA_SERVICE_PORT:-8080}:8080"
      - "${ATOMA_PROXY_SERVICE_PORT:-8081}:8081"
    depends_on:
      - db
    networks:
      - atoma-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atoma-proxy.rule=Host(`api.atomacloud.com`)"
      - "traefik.http.routers.atoma-proxy.entrypoints=websecure"
      - "traefik.http.routers.atoma-proxy.tls.certresolver=myresolver"
      - "traefik.http.services.atoma-proxy-service.loadbalancer.server.port=8080"

volumes:
  postgres-data:
  sui-config-volume:
  letsencrypt:

networks:
  atoma-network:
    driver: bridge
