services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: atoma
      POSTGRES_USER: atoma
      POSTGRES_PASSWORD: atoma
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.test.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"