services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: atoma
      POSTGRES_USER: atoma
      POSTGRES_PASSWORD: atoma
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"

volumes:
  postgres-data:
