global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"] # This should match your collector service name
    metric_relabel_configs:
      - action: labelmap
        regex: ^atoma_(.+)$
        replacement: $1

  - job_name: "atoma-proxy"
    static_configs:
      - targets: ["localhost:8889"] # Local development scraping

  - job_name: "postgres_archival"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["postgres-db:5432"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.*):.*"
        replacement: "$1"
