# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Log configuration
log:
  level: INFO

# Access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

# Metrics configuration
metrics:
  prometheus: {}

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# Certificate resolvers
certificatesResolvers:
  myresolver:
    acme:
      email: ${ACME_EMAIL}
      storage: /acme.json
      tlsChallenge: true 