[package]
name = "atoma-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
atoma-state.workspace = true
atoma-sui.workspace = true
axum.workspace = true
clap.workspace = true
config.workspace = true
flume.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "time"] }
tracing.workspace = true
sui-keys.workspace = true
sui-sdk.workspace = true
blake2 = "0.10.6"
reqwest = "0.12.9"
