apiVersion: v2
name: atoma-proxy
description: A Helm chart for Atoma Proxy
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Atoma Network
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: "15.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: loki
    version: "5.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: tempo
    version: "1.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
