# Development environment settings
global:
  environment: development
  domain: atoma.network

atomaProxy:
  image:
    repository: ghcr.io/atoma-network/atoma-proxy
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: api-dev.atoma.network
        paths:
          - path: /
            pathType: Prefix
            service: http
      - host: credentials-dev.atoma.network
        paths:
          - path: /
            pathType: Prefix
            service: credentials
      - host: prover-dev.atoma.network
        paths:
          - path: /
            pathType: Prefix
            service: prover
  config:
    logLevel: "debug"
    environment: "development"
  extraEnv:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector:4317

# PostgreSQL settings
postgresql:
  enabled: true
  auth:
    database: atoma_proxy_dev
    username: atoma_proxy_dev
    password: "dev_password" # Change this in production
  primary:
    persistence:
      size: 5Gi
  service:
    port: 5432

# Monitoring stack settings
prometheus:
  enabled: true
  server:
    persistentVolume:
      size: 5Gi
  alertmanager:
    persistentVolume:
      size: 1Gi

grafana:
  enabled: true
  persistence:
    size: 5Gi
  admin:
    existingSecret: "grafana-admin"
    userKey: admin-user
    passwordKey: admin-password
  security:
    adminPassword: "admin123"
  ingress:
    enabled: true
    hosts:
      - grafana-dev.atoma.network

loki:
  enabled: false # Temporarily disable Loki
  persistence:
    size: 5Gi
  ingress:
    enabled: true
    hosts:
      - loki-dev.atoma.network
  storage:
    type: filesystem
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2022-01-11
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki
  limits_config:
    retention_period: 744h
  memberlist:
    join_members:
      - loki-memberlist

tempo:
  enabled: true
  persistence:
    size: 5Gi
  ingress:
    enabled: true
    hosts:
      - tempo-dev.atoma.network
